ALTER TABLE orders ADD COLUMN IF NOT EXISTS amount_paid INTEGER DEFAULT 0;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS paid_at TIMESTAMPTZ;
ALTER TABLE orders ADD COLUMN IF NOT EXISTS payment_notes TEXT DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_orders_paid_at ON orders(paid_at);
